<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXq5Otxe\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXq5Otxe/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXq5Otxe.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXq5Otxe\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXq5Otxe\App_KernelDevDebugContainer([
    'container.build_hash' => 'Xq5Otxe',
    'container.build_id' => 'ce30c8af',
    'container.build_time' => 1658948611,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXq5Otxe');
