<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerE6uHAwm\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerE6uHAwm/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerE6uHAwm.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerE6uHAwm\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerE6uHAwm\App_KernelDevDebugContainer([
    'container.build_hash' => 'E6uHAwm',
    'container.build_id' => '45bcbea3',
    'container.build_time' => 1660941112,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerE6uHAwm');
