<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerByIF2Ig\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerByIF2Ig/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerByIF2Ig.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerByIF2Ig\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerByIF2Ig\App_KernelDevDebugContainer([
    'container.build_hash' => 'ByIF2Ig',
    'container.build_id' => 'fad64c6a',
    'container.build_time' => 1660744750,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerByIF2Ig');
