<?php

namespace ContainerGADtLjr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_W1nPa6cService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.w1nPa6c' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.w1nPa6c'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\IngredientController::delete' => ['privates', '.service_locator.c0gwR3Q', 'get_ServiceLocator_C0gwR3QService', true],
            'App\\Controller\\IngredientController::edit' => ['privates', '.service_locator.c0gwR3Q', 'get_ServiceLocator_C0gwR3QService', true],
            'App\\Controller\\IngredientController::index' => ['privates', '.service_locator.7FZkCkl', 'get_ServiceLocator_7FZkCklService', true],
            'App\\Controller\\IngredientController::new' => ['privates', '.service_locator.tgVVt0z', 'get_ServiceLocator_TgVVt0zService', true],
            'App\\Controller\\RecipeController::delete' => ['privates', '.service_locator.BaExLhf', 'get_ServiceLocator_BaExLhfService', true],
            'App\\Controller\\RecipeController::edit' => ['privates', '.service_locator.BaExLhf', 'get_ServiceLocator_BaExLhfService', true],
            'App\\Controller\\RecipeController::index' => ['privates', '.service_locator.6nHral7', 'get_ServiceLocator_6nHral7Service', true],
            'App\\Controller\\RecipeController::new' => ['privates', '.service_locator.tgVVt0z', 'get_ServiceLocator_TgVVt0zService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.zFcJjKU', 'get_ServiceLocator_ZFcJjKUService', true],
            'App\\Controller\\SecurityController::registration' => ['privates', '.service_locator.tgVVt0z', 'get_ServiceLocator_TgVVt0zService', true],
            'App\\Controller\\UserController::edit' => ['privates', '.service_locator.AbuX7CZ', 'get_ServiceLocator_AbuX7CZService', true],
            'App\\Controller\\UserController::editPassword' => ['privates', '.service_locator.q1Q7DY5', 'get_ServiceLocator_Q1Q7DY5Service', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
            'App\\Controller\\IngredientController:delete' => ['privates', '.service_locator.c0gwR3Q', 'get_ServiceLocator_C0gwR3QService', true],
            'App\\Controller\\IngredientController:edit' => ['privates', '.service_locator.c0gwR3Q', 'get_ServiceLocator_C0gwR3QService', true],
            'App\\Controller\\IngredientController:index' => ['privates', '.service_locator.7FZkCkl', 'get_ServiceLocator_7FZkCklService', true],
            'App\\Controller\\IngredientController:new' => ['privates', '.service_locator.tgVVt0z', 'get_ServiceLocator_TgVVt0zService', true],
            'App\\Controller\\RecipeController:delete' => ['privates', '.service_locator.BaExLhf', 'get_ServiceLocator_BaExLhfService', true],
            'App\\Controller\\RecipeController:edit' => ['privates', '.service_locator.BaExLhf', 'get_ServiceLocator_BaExLhfService', true],
            'App\\Controller\\RecipeController:index' => ['privates', '.service_locator.6nHral7', 'get_ServiceLocator_6nHral7Service', true],
            'App\\Controller\\RecipeController:new' => ['privates', '.service_locator.tgVVt0z', 'get_ServiceLocator_TgVVt0zService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.zFcJjKU', 'get_ServiceLocator_ZFcJjKUService', true],
            'App\\Controller\\SecurityController:registration' => ['privates', '.service_locator.tgVVt0z', 'get_ServiceLocator_TgVVt0zService', true],
            'App\\Controller\\UserController:edit' => ['privates', '.service_locator.AbuX7CZ', 'get_ServiceLocator_AbuX7CZService', true],
            'App\\Controller\\UserController:editPassword' => ['privates', '.service_locator.q1Q7DY5', 'get_ServiceLocator_Q1Q7DY5Service', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
        ], [
            'App\\Controller\\IngredientController::delete' => '?',
            'App\\Controller\\IngredientController::edit' => '?',
            'App\\Controller\\IngredientController::index' => '?',
            'App\\Controller\\IngredientController::new' => '?',
            'App\\Controller\\RecipeController::delete' => '?',
            'App\\Controller\\RecipeController::edit' => '?',
            'App\\Controller\\RecipeController::index' => '?',
            'App\\Controller\\RecipeController::new' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\SecurityController::registration' => '?',
            'App\\Controller\\UserController::edit' => '?',
            'App\\Controller\\UserController::editPassword' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\IngredientController:delete' => '?',
            'App\\Controller\\IngredientController:edit' => '?',
            'App\\Controller\\IngredientController:index' => '?',
            'App\\Controller\\IngredientController:new' => '?',
            'App\\Controller\\RecipeController:delete' => '?',
            'App\\Controller\\RecipeController:edit' => '?',
            'App\\Controller\\RecipeController:index' => '?',
            'App\\Controller\\RecipeController:new' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\SecurityController:registration' => '?',
            'App\\Controller\\UserController:edit' => '?',
            'App\\Controller\\UserController:editPassword' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
