<?php

namespace ContainerQVuf9DX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRecipeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.BaExLhf.App\Entity\Recipe' shared service.
     *
     * @return \App\Entity\Recipe
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.BaExLhf": it references class "App\\Entity\\Recipe" but no such service exists.');
    }
}
